databases:
  - name: database
    databaseName: foil

services:
  - name: web-service
    type: web
    env: node
    plan: standard
    buildCommand: pnpm --prefix packages/data install
    startCommand: pnpm --prefix packages/data start:service
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString
    repo: https://github.com/foilxyz/foil
    branch: staging

  - name: background-worker
    type: worker
    env: node
    plan: standard
    buildCommand: pnpm --prefix packages/data install
    startCommand: pnpm --prefix packages/data start:worker
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString
    repo: https://github.com/foilxyz/foil
    branch: staging
