name="foil-omnibus"
version="0.1"

[clone.ethgas_epoch1]
source="foil"
target="foil@ethgas_epoch1"
options.endTime = "1720051200" # 4th of july, 2024
options.resolver = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266" # Default anvil signer
options.baseAssetMinPrice = "<%= parseEther('5') %>"
options.baseAssetMaxPrice = "<%= parseEther('200') %>"
options.feeRate = "10000" # 1%
options.depends = []