name="foil"
version="0.1"

[var.settings]
startTime = "1727740800"
endTime = "1735689599"
baseAssetMinPrice = "7000" # 2
baseAssetMaxPrice = "46000" # 100
feeRate = "10000" # 1%
resolver = "0x0000000000000000000000000000000000000000"
depends = []

[clone.Uniswap]
source="uniswap"
target="foil@uniswap"

[clone.CollateralAsset]
source="mintable-token@permissionless-mint"
target="foil@test-collateral-asset"
var.symbol="cbETH"

[deploy.ReentrancyGuard]
artifact = "ReentrancyGuard"

[deploy.UniV3Abstraction]
artifact = "UniV3Abstraction"

[deploy.FoilConfigurationModule]
artifact="FoilConfigurationModule"
libraries.ReentrancyGuard="<%= contracts.ReentrancyGuard.address %>"
libraries.UniV3Abstraction="<%= contracts.UniV3Abstraction.address %>"
args=[
  "<%= settings.startTime %>",
  "<%= settings.endTime %>",
  "<%= imports.Uniswap.contracts.NonfungiblePositionManager.address %>",
  "<%= imports.Uniswap.contracts.Quoter.address %>",
  "<%= imports.CollateralAsset.contracts.Token.address %>",
  "<%= settings.baseAssetMinPrice %>",
  "<%= settings.baseAssetMaxPrice %>",
  "<%= settings.feeRate %>",
  "<%= settings.resolver %>",
]
depends = ['var.settings', 'deploy.ReentrancyGuard', 'deploy.UniV3Abstraction']

[deploy.FoilLiquidityModule]
artifact="FoilLiquidityModule"
libraries.UniV3Abstraction="<%= contracts.UniV3Abstraction.address %>"

[deploy.FoilSettlementModule]
artifact="FoilSettlementModule"

[deploy.FoilTradeModule]
artifact="FoilTradeModule"

[deploy.FoilNftModule]
artifact="FoilNftModule"

[router.Foil]
contracts=[
  "FoilConfigurationModule",
  "FoilLiquidityModule",
  "FoilSettlementModule",
  "FoilTradeModule",
  "FoilNftModule",
]

# [deploy.FoilVault]
# artifact="FoilVault"