name="foil"
version="0.1"

[var.settings]
startTime = "1721971200"
endTime = "1722057599" #
baseAssetMinPrice = "7000" # 2
baseAssetMaxPrice = "46000" # 100
feeRate = "10000" # 1%
startingPrice = "112045541949572279837463876454" # 1
resolver = "0x07aeeb7e544a070a2553e142828fb30c214a1f86"
asserter = "0xFd9e2642a170aDD10F53Ee14a93FcF2F31924944"
assertionLiveness = "3600"
bondAmount = "5000000000"
priceUnit = "<%= toBytes('Gas/Gwei') %>"

# [pull.Uniswap]
# source="uniswap"

[pull.wstETH]
source="wsteth-token"

[pull.USDC]
source="usdc-token"

[deploy.ReentrancyGuard]
artifact = "ReentrancyGuard"

[deploy.EpochConfigurationModule]
artifact="EpochConfigurationModule"
libraries.ReentrancyGuard="<%= contracts.ReentrancyGuard.address %>"

[deploy.EpochLiquidityModule]
artifact="EpochLiquidityModule"

[deploy.EpochUMASettlementModule]
artifact="EpochUMASettlementModule"

[deploy.EpochTradeModule]
artifact="EpochTradeModule"

[deploy.EpochNftModule]
artifact="EpochNftModule"

[router.Foil]
contracts=[
  "EpochConfigurationModule",
  "EpochLiquidityModule",
  "EpochUMASettlementModule",
  "EpochTradeModule",
  "EpochNftModule",
]

[invoke.createEpoch]
target="Foil"
func="createEpoch"
args=[
  "<%= settings.startTime %>",
  "<%= settings.endTime %>",
  "0x1238536071E1c677A632429e3655c799b22cDA52",
  "0xEd1f6473345F45b75F8179591dd5bA1888cf2FB3",
  "0x3fC91A3afd70395Cd496C647d5a6CC9D4B2b7FAD",
  "<%= imports.wstETH.contracts.Token.address %>",
  "<%= settings.baseAssetMinPrice %>",
  "<%= settings.baseAssetMaxPrice %>",
  "<%= settings.feeRate %>",
  "<%= settings.startingPrice %>",
  "<%= settings.resolver %>",
  "<%= settings.asserter %>",
  
]
depends = ['var.settings', 'router.Foil']