name="foil"
version="<%= package.version %>"
privateSourceCode=true

[var.settings]
owner="0xE006B58cA5aB7ba53863012dc3067A14b965C1da"
startTime = "<%= parseInt(timestamp) + 600 %>"
endTime = "<%= parseInt(timestamp) + 600 + 604800 %>"
baseAssetMinPriceTick = "5200" # 1.709
baseAssetMaxPriceTick = "28200" # 17.09
feeRate = "10000" # 1%
startingSqrtPriceX96 = "146497135921788803112962621440" # 3.419
assertionLiveness = "21600" # 6 hours
bondAmount = "5000000000"
priceUnit = "<%= formatBytes32String('wstGwei/gas') %>"
optimisticOracleV3 = "0xFd9e2642a170aDD10F53Ee14a93FcF2F31924944"
depends = []

# [pull.Uniswap]
# source="uniswap"

[pull.wstETH]
source="wsteth-token"

[pull.USDC]
source="usdc-token"

[deploy.ConfigurationModule]
artifact="ConfigurationModule"
args=["<%= settings.owner %>"]

[deploy.LiquidityModule]
artifact="LiquidityModule"

[deploy.UMASettlementModule]
artifact="UMASettlementModule"

[deploy.TradeModule]
artifact="TradeModule"

[deploy.NftModule]
artifact="NftModule"

[deploy.ViewsModule]
artifact="ViewsModule"

[deploy.ERC165Module]
artifact="ERC165Module"

[deploy.SettlementModule]
artifact="SettlementModule"

[router.Foil]
contracts=[
  "ConfigurationModule",
  "LiquidityModule",
  "UMASettlementModule",
  "TradeModule",
  "NftModule",
  "ViewsModule",
  "ERC165Module",
  "SettlementModule"
]
highlight=true

[invoke.initializeMarket]
target="Foil"
func="initializeMarket"
from="<%= settings.owner %>"
args=[
  "<%= settings.owner %>",
  "<%= imports.wstETH.contracts.Token.address %>",
  { baseAssetMinPriceTick = "<%= settings.baseAssetMinPriceTick %>", baseAssetMaxPriceTick = "<%= settings.baseAssetMaxPriceTick %>", feeRate = "<%= settings.feeRate %>", assertionLiveness= "<%= settings.assertionLiveness %>", bondCurrency = "<%= imports.USDC.contracts.Token.address %>", bondAmount = "<%= settings.bondAmount %>", priceUnit = "<%= settings.priceUnit %>", uniswapPositionManager = "0x1238536071E1c677A632429e3655c799b22cDA52", uniswapSwapRouter = "0x65669fe35312947050c450bd5d36e6361f85ec12", uniswapQuoter = "0xC0499C71624d8eD01DAd75Fc29d8dB8889F0096C", optimisticOracleV3 = "<%= settings.optimisticOracleV3 %>" }
]
depends=["router.Foil"]

[invoke.createEpoch]
target="Foil"
from = "<%= settings.owner %>"
func="createEpoch"
args=[
  "<%= settings.startTime %>",
  "<%= settings.endTime %>",
  "<%= settings.startingSqrtPriceX96 %>",
  "4"
]
depends=["invoke.initializeMarket"]