name="foil"
version="0.1"

[var.settings]
startTime = "1719792000" # 2024-07-01 00:00:00 GMT
endTime = "1735689599" # 2024-12-31 23:59:59 GMT
baseAssetMinPrice = "7000" # 2
baseAssetMaxPrice = "46000" # 100
feeRate = "10000" # 1%
startingPrice = "112045541949572279837463876454" # 1
resolver = "0x0000000000000000000000000000000000000000"
asserter = "0x0000000000000000000000000000000000000000"
depends = []

[clone.Uniswap]
source="uniswap"
target="foil@uniswap"

[clone.CollateralAsset]
source="mintable-token@permissionless-mint"
target="foil@test-collateral-asset"
var.symbol="wstETH"

[deploy.ReentrancyGuard]
artifact = "ReentrancyGuard"

[deploy.EpochConfigurationModule]
artifact="EpochConfigurationModule"
libraries.ReentrancyGuard="<%= contracts.ReentrancyGuard.address %>"

[deploy.EpochLiquidityModule]
artifact="EpochLiquidityModule"

[deploy.EpochUMASettlementModule]
artifact="EpochUMASettlementModule"

[deploy.EpochTradeModule]
artifact="EpochTradeModule"

[deploy.EpochNftModule]
artifact="EpochNftModule"

[router.Foil]
contracts=[
  "EpochConfigurationModule",
  "EpochLiquidityModule",
  "EpochUMASettlementModule",
  "EpochTradeModule",
  "EpochNftModule",
]

[invoke.createEpoch]
target="Foil"
func="createEpoch"
args=[
  "<%= settings.startTime %>",
  "<%= settings.endTime %>",
  "<%= imports.Uniswap.contracts.NonfungiblePositionManager.address %>",
  "<%= imports.Uniswap.contracts.Quoter.address %>",
  "<%= imports.Uniswap.contracts.SwapRouter.address %>",
  "<%= imports.CollateralAsset.contracts.Token.address %>",
  "<%= settings.baseAssetMinPrice %>",
  "<%= settings.baseAssetMaxPrice %>",
  "<%= settings.feeRate %>",
  "<%= settings.startingPrice %>",
  "<%= settings.resolver %>",
  "<%= settings.asserter %>",
  
]
depends = ['var.settings', 'router.Foil']

[invoke.gimmeTokens]
target="CollateralAsset.Token"
func="mint"
args=["<%= parseEther('1000') %>", "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"]
depends=["clone.CollateralAsset"]