name="foil"
version="0.1"

[var.settings]
startTime = "1727740800"
endTime = "1735689599"
resolver = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266" # Default anvil signer
baseAssetMinPrice = "7000" # 2
baseAssetMaxPrice = "46000" # 100
feeRate = "10000" # 1%
depends = []

[clone.Uniswap]
source="uniswap"
target="foil@uniswap"

[clone.CollateralAsset]
source="mintable-token@permissionless-mint"
target="foil@test-collateral-asset"
var.symbol="cbETH"

[deploy.ReentrancyGuard]
artifact = "ReentrancyGuard"

[deploy.UniV3Abstraction]
artifact = "UniV3Abstraction"

[deploy.Foil]
artifact="Foil"
libraries.ReentrancyGuard="<%= contracts.ReentrancyGuard.address %>"
libraries.UniV3Abstraction="<%= contracts.UniV3Abstraction.address %>"
args=[
  "<%= settings.startTime %>",
  "<%= settings.endTime %>",
  "<%= imports.Uniswap.contracts.NonfungiblePositionManager.address %>",
  "<%= imports.Uniswap.contracts.Quoter.address %>",
  "<%= settings.resolver %>",
  "<%= imports.CollateralAsset.contracts.MintableToken.address %>",
  "<%= settings.baseAssetMinPrice %>",
  "<%= settings.baseAssetMaxPrice %>",
  "<%= settings.feeRate %>",
]
CREATE2="true"
depends = ['var.settings', 'deploy.ReentrancyGuard', 'deploy.UniV3Abstraction']