name="foil"
version="0.1"

[var.settings]
endTime = "1720051200" # 4th of july, 2024
uniswapPositionManager = "0x03a520b32C04BF3bEEf7BEb72E919cf822Ed34f1" # Base, lets use base fork for now
resolver = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266" # Default anvil signer
baseAssetMinPrice = "<%= parseEther('5') %>"
baseAssetMaxPrice = "<%= parseEther('200') %>"
feeRate = "10000" # 1%
depends = []

[clone.CollateralAsset]
source="mintable-token@permissionless-mint"
target="foil@test-collateral-asset"

[deploy.ReentrancyGuard]
artifact = "ReentrancyGuard"

[deploy.UniV3Abstraction]
artifact = "UniV3Abstraction"

[deploy.Foil]
artifact="Foil"
libraries.ReentrancyGuard="<%= contracts.ReentrancyGuard.address %>"
libraries.UniV3Abstraction="<%= contracts.UniV3Abstraction.address %>"
args=[
  "<%= settings.endTime %>",
  "<%= settings.uniswapPositionManager %>",
  "<%= settings.resolver %>",
  "<%= imports.CollateralAsset.contracts.MintableToken.address %>",
  "<%= settings.baseAssetMinPrice %>",
  "<%= settings.baseAssetMaxPrice %>",
  "<%= settings.feeRate %>",
]
depends = ['var.settings', 'deploy.ReentrancyGuard', 'deploy.UniV3Abstraction']