'use client';

import { blo } from 'blo';
import Image from 'next/image';
<<<<<<< HEAD
import { useEffect } from 'react';
import { fromHex } from 'viem';
import { Button } from '@sapience/ui/components/ui/button';
import { Filter } from 'lucide-react';
import { AddressDisplay, useEnsName } from './AddressDisplay';
import { usePredictions } from '~/hooks/graphql/usePredictions';
import { SCHEMA_UID } from '~/lib/constants/eas';
import { useEnrichedMarketGroups } from '~/hooks/graphql/useMarketGroups';
import { tickToPrice } from '~/lib/utils/tickUtils';
import { sqrtPriceX96ToPriceD18 } from '~/lib/utils/util';

// Helper function to check if a market is active
function isMarketActive(market: any): boolean {
  const now = Math.floor(Date.now() / 1000);
  const start = market.startTimestamp;
  const end = market.endTimestamp;

  return (
    market.public &&
    typeof start === 'number' &&
    !Number.isNaN(start) &&
    typeof end === 'number' &&
    !Number.isNaN(end) &&
    now >= start &&
    now < end
  );
}
=======
import { useState, useEffect } from 'react';
import { useAccount } from 'wagmi';
import { connectorsForWallets } from '@rainbow-me/rainbowkit';
import { fromHex } from 'viem';
import { AddressDisplay } from './AddressDisplay';
import { usePredictions } from '~/hooks/graphql/usePredictions';
import { SCHEMA_UID } from '~/lib/constants/eas';
import { useEnrichedMarketGroups } from '~/hooks/graphql/useMarketGroups';
>>>>>>> ccf23b0fa0d1f1f7231e6d389147a20779082e92

export enum Answer {
  Yes = 'yes',
  No = 'no',
}

<<<<<<< HEAD
export enum SelectableTab {
  Selected = 'selected',
  MyPredictions = 'my-predictions',
  // Add all FOCUS_AREAS ids:
  EconomyFinance = 'economy-finance',
  DecentralizedCompute = 'decentralized-compute',
  EnergyDepin = 'energy-depin',
  ClimateChange = 'climate-change',
  Geopolitics = 'geopolitics',
  Biosecurity = 'biosecurity',
  SpaceExploration = 'space-exploration',
  EmergingTechnologies = 'emerging-technologies',
  Athletics = 'athletics',
=======
export enum SpecialTab {
  Selected = 'selected',
  MyPredictions = 'my-predictions',
>>>>>>> ccf23b0fa0d1f1f7231e6d389147a20779082e92
}

interface Comment {
  id: string;
  address: string;
  content: string;
  timestamp: string;
  prediction?: string;
  question: string; // Added question field
  category?: string; // Added category field
  answer: Answer;
  marketClassification?: string; // Added marketClassification field
  optionIndex?: number;
  totalOptions?: number;
  numericValue?: number;
  lowerBound?: number;
  upperBound?: number;
<<<<<<< HEAD
  isActive?: boolean; // Added isActive field
=======
>>>>>>> ccf23b0fa0d1f1f7231e6d389147a20779082e92
}

interface CommentsProps {
  className?: string;
  question?: string;
<<<<<<< HEAD
  selectedCategory?: SelectableTab | null;
  address?: string | null;
  refetchTrigger?: number;
  selectedAddressFilter?: string | null;
  onAddressFilterChange?: (address: string | null) => void;
}

=======
  showAllForecasts?: boolean;
  selectedCategory?: string | null;
  address?: string | null;
  refetchTrigger?: number;
}

/*
TODO for schema:
id -> autogenerated?
content -> string
timestamp -> timestamp
prediction -> uint16 -> percentage
answer -> enum ('yes' | 'no')
question -> string or id?
category -> string (enum)
*/

// Mock data with multiple questions and categories
const allComments: Comment[] = [
  {
    id: '1',
    address: '0x742d35Cc6e1590b7c89C4f8B6C8e0DB66C72Ca2D',
    content: 'ETH has strong fundamentals with the upcoming ETF approvals and institutional adoption. The $5K target seems achievable given current DeFi growth and staking yields. Bullish on this timeline.',
    timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    prediction: '84% Chance',
    answer: Answer.Yes,
    question: "What will NVIDIA’s earnings per share (EPS) be for Q1 2025?",
    category: 'economy-finance'
  },
  {
    id: '13132',
    address: '0x742d35Cc6e1590b7c89C4f8B6C8e0DB66C72Ca2D',
    content: 'BTC sucks!',
    timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    prediction: '84% Chance',
    answer: Answer.No,
    question: "What will NVIDIA’s earnings per share (EPS) be for Q1 2025?",
    category: 'economy-finance'
  },
  {
    id: '4',
    address: '0x17C360CBfa39E218fB49CA754eC53af31684DD05',
    content: 'Looking at current AI leaders like NVIDIA (~$1.8T) and potential of companies like OpenAI going public, $5T is ambitious but possible. The AI race is accelerating exponentially.',
    timestamp: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    answer: Answer.No,
    prediction: '76% Chance',
    question: "What will NVIDIA’s earnings per share (EPS) be for Q1 2025?",
    category: 'economy-finance'
  },
  {
    id: '5',
    address: '0xa0b86a33e6329ec8ae87e5e53b4f99e7c0d2e5c3',
    content: 'Renewable capacity additions are breaking records. Solar/wind costs have plummeted and storage tech is improving rapidly. The 50% threshold is within reach given current trajectory.',
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    answer: Answer.Yes,
    prediction: '88% Chance',
    question: "What will be the average air temperature in New York City in a given period?",
    category: 'climate-change'
  },
  // Additional comments for when showing single question
  {
    id: '2',
    address: '0x8ba1f109551bd432803012645hac136c08ce5fff',
    content: 'Not sure about this one. The volatility has been crazy lately and I think we might see a correction soon.',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    prediction: '23% Chance',
    answer: Answer.No,
    question: "Will ETH be above $2900 by July 11th",
    category: 'economy-finance'
  },
  {
    id: '3',
    address: '0x17C360CBfa39E218fB49CA754eC53af31684DD05',
    content: 'Just placed a large wager on YES. The fundamentals look strong and I expect this to resolve positively.',
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    prediction: '92% Chance',
    answer: Answer.Yes,
    question: "Will ETH be above $2900 by July 11th",
    category: 'economy-finance'
  },
  // Additional comments for different categories
  {
    id: '6',
    address: '0x1234567890123456789012345678901234567890',
    content: 'AI models are getting exponentially better. With the current pace of advancement, a $5T valuation is definitely possible.',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    prediction: '82% Chance',
    answer: Answer.Yes,
    question: "US military action against Iran before July?",
    category: 'geopolitics'
  },
  {
    id: '7',
    address: '0xabcdef1234567890abcdef1234567890abcdef12',
    content: 'Solar panel efficiency keeps improving and costs keep falling. The renewable transition is unstoppable.',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    prediction: '11% Chance',
    answer: Answer.Yes,
    question: "US military action against Iran before July?",
    category: 'geopolitics'
  }
];

>>>>>>> ccf23b0fa0d1f1f7231e6d389147a20779082e92
// Helper to extract decoded data from attestation, handling .decodedData, .value.value, etc.
function getDecodedDataFromAttestation(att: any): {
  marketAddress: string;
  marketId: number;
  prediction: bigint;
  commentText: string;
} {
<<<<<<< HEAD
  console.log('marketID', att.decodedData[1].value.value);
  console.log('prediction', att.decodedData[2].value.value);
=======
  console.log("marketID", att.decodedData[1].value.value);
  console.log("prediction", att.decodedData[2].value.value);
>>>>>>> ccf23b0fa0d1f1f7231e6d389147a20779082e92
  return {
    marketAddress: att.decodedData[0].value.value,
    // marketId: att.decodedData[1].value.value,
    // prediction: att.decodedData[2].value.value,
    marketId: fromHex(att.decodedData[1].value.value.hex, 'number'),
    prediction: fromHex(att.decodedData[2].value.value.hex, 'bigint'),
<<<<<<< HEAD
    commentText: att.decodedData[3].value.value,
  };
}

// Component to handle ENS resolution for filter button
const FilterButton = ({
  address,
  onFilter,
}: {
  address: string;
  onFilter: (displayName: string) => void;
}) => {
  const { data: ensName } = useEnsName(address);
  const displayName = ensName || address;

  return (
    <Button
      variant="ghost"
      size="sm"
      className="h-5 w-5 p-0 ml-1"
      onClick={() => onFilter(displayName)}
      title={`Filter by ${displayName}`}
    >
      <Filter className="h-3 w-3 text-muted-foreground hover:text-foreground" />
    </Button>
  );
};

// Helper to parse EAS attestation data to Comment type for SCHEMA_UID
function attestationToComment(
  att: any,
  marketGroups: any[] | undefined
): Comment {
  // Schema: address marketAddress, uint256 marketId, uint160 prediction, string comment
  const { marketAddress, marketId, prediction, commentText } =
    getDecodedDataFromAttestation(att);
=======
    commentText: att.decodedData[3].value.value
  };
}

// Helper to parse EAS attestation data to Comment type for SCHEMA_UID
function attestationToComment(att: any, marketGroups: any[] | undefined): Comment {
  // Schema: address marketAddress, uint256 marketId, uint160 prediction, string comment
  const {marketAddress, marketId, prediction, commentText} = getDecodedDataFromAttestation(att);
>>>>>>> ccf23b0fa0d1f1f7231e6d389147a20779082e92

  // Find the category, question, and marketClassification using marketGroups
  let category: string | undefined = undefined;
  let question: string = marketId?.toString() || '';
  let marketClassification: string | undefined = undefined;
  let optionName: string | undefined = undefined;
  let baseTokenName: string | undefined = undefined;
  let quoteTokenName: string | undefined = undefined;
  let optionIndex: number | undefined = undefined;
  let totalOptions: number | undefined = undefined;
  let numericValue: number | undefined = undefined;
  let lowerBound: number | undefined = undefined;
  let upperBound: number | undefined = undefined;
<<<<<<< HEAD
  let isActive: boolean = false;
=======
>>>>>>> ccf23b0fa0d1f1f7231e6d389147a20779082e92
  if (marketGroups && marketAddress && marketId) {
    const group = marketGroups.find(
      (g) => g.address?.toLowerCase() === marketAddress.toLowerCase()
    );
    if (group) {
      // Find the market in the group
<<<<<<< HEAD
      const market = group.markets?.find(
        (m: any) => m.marketId?.toString() === marketId?.toString()
      );
      // Check if the market is active
      if (market) {
        isActive = isMarketActive(market);
      }
=======
      const market = group.markets?.find((m: any) => m.marketId?.toString() === marketId?.toString());
>>>>>>> ccf23b0fa0d1f1f7231e6d389147a20779082e92
      if (market && market.question) {
        if (typeof market.question === 'string') {
          question = market.question;
        } else if (market.question.value) {
          question = String(market.question.value);
        } else {
          question = String(market.question);
        }
      }
      if (market && group.category?.slug) {
        category = group.category.slug;
      } else if (group.category?.slug) {
        category = group.category.slug;
      }
      if (group.marketClassification) {
        marketClassification = group.marketClassification;
      }
      if (market && market.optionName) {
        optionName = market.optionName;
      }
      if (group.baseTokenName) baseTokenName = group.baseTokenName;
      if (group.quoteTokenName) quoteTokenName = group.quoteTokenName;
      // Multiple choice: find index and total
      if (marketClassification === '1' && group.markets) {
<<<<<<< HEAD
        optionIndex = group.markets.findIndex(
          (m: any) => m.marketId?.toString() === marketId?.toString()
        );
=======
        optionIndex = group.markets.findIndex((m: any) => m.marketId?.toString() === marketId?.toString());
>>>>>>> ccf23b0fa0d1f1f7231e6d389147a20779082e92
        totalOptions = group.markets.length;
      }
      // Numeric: get value and bounds
      if (marketClassification === '3' && market) {
<<<<<<< HEAD
        numericValue = Number(
          sqrtPriceX96ToPriceD18(prediction) / BigInt(10 ** 36)
        );
        lowerBound =
          market.baseAssetMinPriceTick !== undefined
            ? Number(market.baseAssetMinPriceTick)
            : undefined;
        upperBound =
          market.baseAssetMaxPriceTick !== undefined
            ? Number(market.baseAssetMaxPriceTick)
            : undefined;
=======
        numericValue = Number(prediction);
        lowerBound = market.baseAssetMinPriceTick !== undefined ? Number(market.baseAssetMinPriceTick) : undefined;
        upperBound = market.baseAssetMaxPriceTick !== undefined ? Number(market.baseAssetMaxPriceTick) : undefined;
>>>>>>> ccf23b0fa0d1f1f7231e6d389147a20779082e92
      }
    }
  }

  // Format prediction text based on market type
  let predictionText = '';
  const YES_SQRT_PRICE_X96 = BigInt('79228162514264337593543950336');
<<<<<<< HEAD
  if (marketClassification === '2') {
    // YES_NO
    predictionText = `${prediction === YES_SQRT_PRICE_X96 ? 'Yes' : 'No'} • ${prediction === YES_SQRT_PRICE_X96 ? '100' : '0'}% Chance`;
  } else if (marketClassification === '1') {
    // MULTIPLE_CHOICE
    predictionText = optionName ? `${optionName}` : `Option ID: ${marketId}`;
  } else if (marketClassification === '3') {
    // NUMERIC
    predictionText = `Prediction: ${numericValue?.toString()}${baseTokenName ? ' ' + baseTokenName : ''}${quoteTokenName ? '/' + quoteTokenName : ''}`;
  } else {
    predictionText = `${numericValue}% Chance`;
=======
  if (marketClassification === '2') { // YES_NO
    predictionText = `${prediction === YES_SQRT_PRICE_X96 ? 'Yes' : 'No'} • ${prediction === YES_SQRT_PRICE_X96 ? '100' : '0'}% Chance`;
  } else if (marketClassification === '1') { // MULTIPLE_CHOICE
    predictionText = optionName ? `Option: ${optionName}` : `Option ID: ${marketId}`;
  } else if (marketClassification === '3') { // NUMERIC
    predictionText = `Prediction: ${prediction.toString()}${baseTokenName ? ' ' + baseTokenName : ''}${quoteTokenName ? '/' + quoteTokenName : ''}`;
  } else {
    predictionText = `${prediction}% Chance`;
>>>>>>> ccf23b0fa0d1f1f7231e6d389147a20779082e92
  }

  return {
    id: att.id,
    address: att.attester,
    content: commentText,
    timestamp: new Date(Number(att.rawTime) * 1000).toISOString(),
    prediction: predictionText,
    answer: Answer.Yes, // Not available in this schema, default to Yes
    question,
    category,
    marketClassification,
    optionIndex,
    totalOptions,
    numericValue,
    lowerBound,
    upperBound,
<<<<<<< HEAD
    isActive,
  };
}

const Comments = ({
  className,
  question = undefined,
  selectedCategory = null,
  address = null,
  refetchTrigger,
  selectedAddressFilter = null,
  onAddressFilterChange,
}: CommentsProps) => {
  // Fetch EAS attestations
  const {
    data: easAttestations,
    isLoading: _isEasLoading,
    refetch,
  } = usePredictions({ schemaId: SCHEMA_UID });
=======
  };
}

const Comments = ({ 
  className, 
  question = undefined, 
  showAllForecasts = false,
  selectedCategory = null,
  address = null,
  refetchTrigger
}: CommentsProps) => {
  console.log('question', question);
  // Fetch EAS attestations
  const { address: wagmiAddress } = useAccount();
  const { data: easAttestations, isLoading: isEasLoading, refetch } = usePredictions({ schemaId: SCHEMA_UID });
>>>>>>> ccf23b0fa0d1f1f7231e6d389147a20779082e92

  // Refetch EAS attestations when refetchTrigger changes
  useEffect(() => {
    if (refetch) refetch();
  }, [refetchTrigger, refetch]);

<<<<<<< HEAD
  console.log('easAttestations', easAttestations);
  // Fetch all market groups for category lookup
  const { data: marketGroups } = useEnrichedMarketGroups
    ? useEnrichedMarketGroups()
    : { data: undefined };

  // Convert EAS attestations to Comment objects with category
  const easComments: Comment[] = (easAttestations || []).map((att) =>
    attestationToComment(att, marketGroups)
  );

  // Filter comments based on selected category and question
  const displayComments = (() => {
    let filtered = easComments;
=======
  console.log("easAttestations", easAttestations);
  // Fetch all market groups for category lookup
  const { data: marketGroups } = useEnrichedMarketGroups ? useEnrichedMarketGroups() : { data: undefined };

  // Convert EAS attestations to Comment objects with category
  const easComments: Comment[] = (easAttestations || []).map(att => attestationToComment(att, marketGroups));

  // Merge mock and EAS comments
  const mergedComments = [...allComments, ...easComments];

  // Filter comments based on selected category and question
  const displayComments = (() => {
    let filtered = mergedComments;
>>>>>>> ccf23b0fa0d1f1f7231e6d389147a20779082e92

    // Filter by category if one is selected (but not for 'selected' tab)
    if (
      selectedCategory &&
<<<<<<< HEAD
      selectedCategory !== SelectableTab.Selected &&
      selectedCategory !== SelectableTab.MyPredictions
    ) {
      filtered = filtered.filter(
        (comment) => comment.category === selectedCategory
      );
    }

    // Filter by address if 'my-predictions' tab is selected
    if (selectedCategory === SelectableTab.MyPredictions && address) {
      filtered = filtered.filter(
        (comment) => comment.address.toLowerCase() === address.toLowerCase()
      );
    }

    // Filter by selected address filter
    if (selectedAddressFilter) {
      filtered = filtered.filter(
        (comment) =>
          comment.address.toLowerCase() === selectedAddressFilter.toLowerCase()
      );
=======
      selectedCategory !== SpecialTab.Selected &&
      selectedCategory !== SpecialTab.MyPredictions
    ) {
      filtered = filtered.filter(comment => comment.category === selectedCategory);
    }

    // Filter by address if 'my-predictions' tab is selected
    if (selectedCategory === SpecialTab.MyPredictions && address) {
      filtered = filtered.filter(comment => comment.address.toLowerCase() === address.toLowerCase());
>>>>>>> ccf23b0fa0d1f1f7231e6d389147a20779082e92
    }

    // Filter by question prop if set
    if (question) {
<<<<<<< HEAD
      filtered = filtered.filter((comment) => {
        console.log('filter comment', comment.question, question);
        return comment.question === question;
      });
    }

    // Sort by timestamp descending (most recent first)
    filtered = filtered
      .slice()
      .sort(
        (a, b) =>
          new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()
      );

    // Filter out numeric comments outside the range
    filtered = filtered.filter((comment) => {
      if (comment?.marketClassification === '3') {
        console.log(
          'comment',
          tickToPrice(comment?.lowerBound as number),
          tickToPrice(comment?.upperBound as number),
          comment?.numericValue
        );
      }

      if (
        comment.marketClassification === '3' &&
        comment.numericValue !== undefined &&
        comment.lowerBound !== undefined &&
        comment.upperBound !== undefined
      ) {
        const min = tickToPrice(comment.lowerBound);
        const max = tickToPrice(comment.upperBound);
        const val = comment.numericValue;
        return val >= min && val <= max;
=======
      filtered = filtered.filter(comment => comment.question === question);
    }

    // Sort by timestamp descending (most recent first)
    filtered = filtered.slice().sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());

    // Filter out numeric comments outside the range
    filtered = filtered.filter(comment => {
      if (comment.marketClassification === '3' && comment.numericValue !== undefined && comment.lowerBound !== undefined && comment.upperBound !== undefined) {
        return comment.numericValue >= comment.lowerBound && comment.numericValue <= comment.upperBound;
>>>>>>> ccf23b0fa0d1f1f7231e6d389147a20779082e92
      }
      return true;
    });

<<<<<<< HEAD
    // Filter out inactive comments
    filtered = filtered.filter((comment) => {
      // For attestation comments (from EAS), check if the market is active
      // For mock comments, allow them through (they don't have isActive field)
      return comment.isActive !== false;
    });

    return filtered;
  })();

  return (
    <div className={`${className || ''}`}>
      {selectedCategory === SelectableTab.Selected && !question && (
        <div className="text-center text-muted-foreground py-8">
          Please select a question to submit a prediction and view the
          predictions of other users
        </div>
      )}
      {!(selectedCategory === SelectableTab.Selected && !question) && (
=======
    return filtered;
  })();

  // Helper function to get badge styling based on prediction percentage
  const getPredictionBadgeStyle = (answer: Answer, prediction: string, comment?: Comment) => {
    // Multiple Choice: color by option index
    if (comment?.marketClassification === '1' && comment.optionIndex !== undefined && comment.totalOptions) {
      // Use HSL: hue from 0 to 360
      const hue = Math.round((comment.optionIndex / comment.totalOptions) * 360);
      return `bg-[hsl(${hue},80%,80%)] text-[hsl(${hue},60%,30%)] border-[hsl(${hue},80%,60%)]`;
    }
    // Yes/No: red/green
    if (comment?.marketClassification === '2') {
      if (answer === Answer.Yes) {
        return 'bg-green-500 text-white border-green-600';
      } else {
        return 'bg-red-500 text-white border-red-600';
      }
    }
    // Numeric: interpolate color from red to green
    if (comment?.marketClassification === '3' && comment.numericValue !== undefined && comment.lowerBound !== undefined && comment.upperBound !== undefined) {
      const min = comment.lowerBound;
      const max = comment.upperBound;
      const val = comment.numericValue;
      // Clamp value
      const pct = Math.max(0, Math.min(1, (val - min) / (max - min)));
      // Interpolate from red (0) to yellow (0.5) to green (1)
      let r, g, b;
      if (pct < 0.5) {
        // Red to yellow
        r = 255;
        g = Math.round(255 * (pct / 0.5));
        b = 0;
      } else {
        // Yellow to green
        r = Math.round(255 * (1 - (pct - 0.5) / 0.5));
        g = 255;
        b = 0;
      }
      const bg = `bg-[rgb(${r},${g},${b})]`;
      const text = 'text-black';
      const border = 'border-black/20';
      return `${bg} ${text} ${border}`;
    }
    // Fallback: gray
    return 'bg-gray-100 text-gray-700 border-gray-300';
  };


  return (
    <div className={`${className || ''}`}>
      {selectedCategory === SpecialTab.Selected && !question && (
        <div className="text-center text-muted-foreground py-8">
          Please select a question to submit a prediction and view the predictions of other users
        </div>
      )}
      {!(selectedCategory === SpecialTab.Selected && !question) && (
>>>>>>> ccf23b0fa0d1f1f7231e6d389147a20779082e92
        <>
          {displayComments.length === 0 && (
            <div className="text-center text-muted-foreground py-8">
              No comments for selected filters...
            </div>
          )}
          {displayComments.map((comment, index) => (
            <div key={comment.id} className="relative">
              {/* Divider */}
              {index > 0 && <div className="border-t border-border" />}
              <div className="relative bg-background">
                <div className="px-6 py-5 space-y-4">
                  {/* Question and Prediction */}
                  <div className="space-y-2">
                    <h2 className="text-[17px] font-medium text-foreground leading-[1.35] tracking-[-0.01em]">
                      {comment.question}
                    </h2>
                    {/* Prediction and Signature on same line */}
                    <div className="flex items-center gap-4">
                      {/* Prediction badge/text based on market type */}
<<<<<<< HEAD
                      {comment.prediction &&
                        (() => {
                          return (
                            <span
                              className={`inline-flex items-center h-6 px-2.5 text-xs font-semibold rounded-full border`}
                            >
                              {comment.prediction}
                            </span>
                          );
                        })()}
=======
                      {comment.prediction && (
                        <span className={`inline-flex items-center h-6 px-2.5 text-xs font-semibold rounded-full border ${getPredictionBadgeStyle(comment.answer, comment.prediction, comment)}`}>
                          {comment.marketClassification === '2' ? (
                            // YES_NO
                            comment.prediction
                          ) : comment.marketClassification === '1' ? (
                            // MULTIPLE_CHOICE
                            comment.prediction
                          ) : comment.marketClassification === '3' ? (
                            // NUMERIC
                            comment.prediction
                          ) : (
                            // fallback
                            comment.prediction
                          )}
                        </span>
                      )}
>>>>>>> ccf23b0fa0d1f1f7231e6d389147a20779082e92
                      {/* Signature */}
                      <div className="flex items-center gap-2">
                        <div className="relative">
                          <Image
                            alt={comment.address}
                            src={blo(comment.address as `0x${string}`)}
                            className="w-5 h-5 rounded-full ring-1 ring-border/50"
                            width={20}
                            height={20}
                          />
                        </div>
                        <div className="flex items-center gap-2 text-xs text-muted-foreground/80 font-medium">
                          <AddressDisplay
                            address={comment.address}
                            disableProfileLink={false}
                            className="text-xs"
                          />
                          <span className="text-muted-foreground/50">·</span>
                          <span className="text-muted-foreground/70">
<<<<<<< HEAD
                            {new Date(comment.timestamp).toLocaleString(
                              undefined,
                              {
                                year: 'numeric',
                                month: 'short',
                                day: 'numeric',
                                hour: '2-digit',
                                minute: '2-digit',
                              }
                            )}
                          </span>
                          {/* Filter button for this address */}
                          <FilterButton
                            address={comment.address}
                            onFilter={(displayName) =>
                              onAddressFilterChange?.(displayName)
                            }
                          />
=======
                            {new Date(comment.timestamp).toLocaleString(undefined, {
                              year: 'numeric',
                              month: 'short',
                              day: 'numeric',
                              hour: '2-digit',
                              minute: '2-digit',
                            })}
                          </span>
>>>>>>> ccf23b0fa0d1f1f7231e6d389147a20779082e92
                        </div>
                      </div>
                    </div>
                  </div>
                  {/* Comment content */}
                  <div className="text-base leading-[1.5] text-foreground/90 tracking-[-0.005em]">
                    {comment.content}
                  </div>
                </div>
              </div>
            </div>
          ))}
        </>
      )}
    </div>
  );
};

<<<<<<< HEAD
export default Comments;
=======
export default Comments; 
>>>>>>> ccf23b0fa0d1f1f7231e6d389147a20779082e92
