name="parlay-pool"
version="1.0.0"
preset="test"

[var.settings]
collateralToken = "0x211Cc4DD073734dA055fbF44a2b4667d5E5fE5d2" # sUSDe on Base
maxParlayMarkets = "5"
minCollateral = "100000000000000000000" # 100 sUSDe (18 decimals)
minRequestExpirationTime = "30" # 60 seconds
maxRequestExpirationTime = "86400" # 1 day

[deploy.ParlayNFTMaker]
artifact="ParlayNFT"
args=[
  "Parlay Maker",
  "PMKR"
]

[deploy.ParlayNFTTaker]
artifact="ParlayNFT"
args=[
  "Parlay Taker",
  "PTKR"
]

[deploy.ParlayPool]
artifact="ParlayPool"
args=[
  "<%= settings.collateralToken %>",
  "<%= ParlayNFTMaker.address %>",
  "<%= ParlayNFTTaker.address %>",
  "<%= settings.maxParlayMarkets %>",
  "<%= settings.minCollateral %>",
  "<%= settings.minRequestExpirationTime %>",
  "<%= settings.maxRequestExpirationTime %>"
]
depends=["ParlayNFTMaker", "ParlayNFTTaker"]
highlight=true

[invoke.transferMakerNFTOwnership]
target="ParlayNFTMaker"
func="transferOwnership"
args=[
  "<%= ParlayPool.address %>"
]
depends=["ParlayPool"]

[invoke.transferTakerNFTOwnership]
target="ParlayNFTTaker"
func="transferOwnership"
args=[
  "<%= ParlayPool.address %>"
]
depends=["ParlayPool"] 